export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // MediFlow OS Design System Colors
        surface: '#001525',
        'surface-dim': '#001525',
        'surface-bright': '#093c5d',
        'surface-container-lowest': '#000f1d',
        'surface-container-low': '#001d32',
        'surface-container': '#002238',
        'surface-container-high': '#002c48',
        'surface-container-highest': '#013858',
        'on-surface': '#cde5ff',
        'on-surface-variant': '#bacac4',
        'inverse-surface': '#cde5ff',
        'inverse-on-surface': '#003352',
        outline: '#85948f',
        'outline-variant': '#3c4a45',
        'surface-tint': '#39debf',
        primary: '#f4fffa',
        'on-primary': '#00382e',
        'primary-container': '#5df8d8',
        'on-primary-container': '#00705e',
        'inverse-primary': '#006b5a',
        secondary: '#95cdf3',
        'on-secondary': '#00344b',
        'secondary-container': '#024e6f',
        'on-secondary-container': '#87bfe4',
        tertiary: '#f5ffff',
        'on-tertiary': '#003739',
        'tertiary-container': '#8ff0f6',
        'on-tertiary-container': '#006e73',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#60fbda',
        'primary-fixed-dim': '#39debf',
        'on-primary-fixed': '#00201a',
        'on-primary-fixed-variant': '#005143',
        'secondary-fixed': '#c6e7ff',
        'secondary-fixed-dim': '#95cdf3',
        'on-secondary-fixed': '#001e2e',
        'on-secondary-fixed-variant': '#004c6c',
        'tertiary-fixed': '#91f2f8',
        'tertiary-fixed-dim': '#74d6dc',
        'on-tertiary-fixed': '#002021',
        'on-tertiary-fixed-variant': '#004f53',
        background: '#001525',
        'on-background': '#cde5ff',
        'surface-variant': '#013858',
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Geist", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        // Typography variants
        'display-lg': ["Geist"],
        'headline-lg': ["Geist"],
        'headline-lg-mobile': ["Geist"],
        'body-md': ["Inter"],
        'data-label': ["JetBrains Mono"],
        'metric-xl': ["JetBrains Mono"],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'data-label': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'metric-xl': ['40px', { lineHeight: '1.0', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'panel-gap': '16px',
      },
      backdropBlur: {
        glass: '20px',
      },
      boxShadow: {
        'glow-cyan': '0 0 20px rgba(93, 248, 216, 0.4)',
        'glow-cyan-strong': '0 0 30px rgba(93, 248, 216, 0.6)',
        glass: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
      },
    },
  },
  plugins: [],
};
